name: Versioning 
description: Check versioning

inputs:
  repository:
    description: Repository
    required: true
    default: ${{ github.repository }}
  from:
    description: From branch
    required: true
    default: ${{ github.ref }}
  to:
    description: To branch
    requried: true
    default: ${{ github.event.repository.default_branch }}
  file:
    description: File
    required: true
    default: cargo

runs:
  using: composite
  steps:
    - shell: bash
      run: cargo build --release
    - shell: bash
      run: ./target/release/versioning ${{ inputs.repository }} ${{ inputs.from }} ${{ inputs.to }} ${{ inputs.file }}
