---
name: release 

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - Cargo.toml
      - Cargo.lock
      - action.yaml

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - run: cargo build --release

      - uses: o0th/get-version@0.2.1
      - run: echo "VERSION=$(get-version)" >> $GITHUB_ENV

      - uses: o0th/create-tag@0.2.0
      - run: |
        local username=$(echo "{{ github.repository }}" | cut -d '/' -f1)
        local repository=$(echo "{{ github.repository }}" | cut -d '/' -f2)
        local version=${{ env.VERSION }}
        local sha=${{ github.sha }}
        create-tag $username $repository $version $sha

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          name: "check-version ${{ env.VERSION }}"
          bodyFile: ".github/changelogs/${{ env.VERSION }}.md"
          artifacts: "./target/release/check-version"
