---
name: release 

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - run: cargo build --release

      - uses: o0th/get-version@0.2.1
      - run: echo "VERSION=$(get-version)" >> $GITHUB_ENV

      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${process.env.VERSION}`,
              sha: context.sha
            })

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          name: "check-version ${{ env.VERSION }}"
          bodyFile: ".github/changelogs/${{ env.VERSION }}.md"
          artifacts: "./target/release/check-version"
