---
name: release 

on:
  push:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - run: cargo build --release

      - uses: o0th/get-version@0.2.1
      - run: echo "VERSION=$(get-version)" >> $GITHUB_ENV

      - uses: o0th/create-tag@0.2.0
      - run: echo "$(echo '$GITHUB_REPOSITORY' | sed ':/: :')"
      - run: create-tag $(echo "$GITHUB_REPOSITORY" | sed "s|/| |") ${{ github.sha }} refs/tags/${{ env.VERSION }}
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          name: "check-version ${{ env.VERSION }}"
          bodyFile: ".github/changelogs/${{ env.VERSION }}.md"
          artifacts: "./target/release/check-version"
