---
name: testing

on:
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:

      - name: Set up source
        uses: actions/checkout@v2

      - run: cargo build --release
      - run: ./target/release/versioning
